version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ./target/ecommerce-0.0.1-SNAPSHOT.jar:/app/ecommerce-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PORT: 3306
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    command: ["java", "-jar", "ecommerce-0.0.1-SNAPSHOT.jar"]

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
    mysql_data: